name: deploy-book

# Only run this when the master branch changes
on:
  push:
    branches:
    - main
    paths:
    - docs/*.md
    - notebooks/**

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # Install dependencies
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r docs/requirements.txt

    # Build the book
    - name: Build the book
      run: |
        mv notebooks docs/
        python docs/scripts/convert.py --actions
        jupyter-book build docs

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v4.0.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html